[package]
name = "from-athena-derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
syn = "2.0.58"
quote = "1.0.35"
aws-sdk-athena = "1.19.0"
anyhow = "1.0.82"
